#!/bin/bash
FLUENTD_FLUSH_INTERVAL=${FLUENTD_FLUSH_INTERVAL:-10s}
FLUENTD_FLUSH_THREADS=${FLUENTD_FLUSH_THREADS:-1}
FLUENTD_RETRY_LIMIT=${FLUENTD_RETRY_LIMIT:-10}
FLUENTD_DISABLE_RETRY_LIMIT=${FLUENTD_DISABLE_RETRY_LIMIT:-true}
FLUENTD_RETRY_WAIT=${FLUENTD_RETRY_WAIT:-1s}
FLUENTD_MAX_RETRY_WAIT=${FLUENTD_MAX_RETRY_WAIT:-60s}
FLUENTD_BUFFER_CHUNK_LIMIT=${FLUENTD_BUFFER_CHUNK_LIMIT:-8m}
FLUENTD_BUFFER_QUEUE_LIMIT=${FLUENTD_BUFFER_QUEUE_LIMIT:-8192}
FLUENTD_BUFFER_TYPE=${FLUENTD_BUFFER_TYPE:-memory}
FLUENTD_BUFFER_PATH=${FLUENTD_BUFFER_PATH:-/var/fluentd/buffer}
FLUENTD_LOGSTASH_PREFIX=${FLUENTD_LOGSTASH_PREFIX:-logstash}

conf_file=/etc/td-agent/td-agent.conf

cat << EOF >> ${conf_file}
# Do not directly collect fluentd's own logs to avoid infinite loops.
<match fluent.**>
  type null
</match>

<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag kubernetes.*
  format json
  read_from_head true
</source>

<source>
  type systemd
  path /var/log/journal
  filters [{ "_SYSTEMD_UNIT": "docker.service" }]
  pos_file docker.pos
  tag docker
  read_from_head true
</source>

<source>
  type systemd
  path /var/log/journal
  filters [{ "_SYSTEMD_UNIT": "etcd2.service" }]
  pos_file etcd2.pos
  tag etcd2
  read_from_head true
</source>

<source>
  type systemd
  path /var/log/journal
  filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
  pos_file kubelet.pos
  tag kubelet
  read_from_head true
</source>

<source>
  type systemd
  path /var/log/journal
  filters [{ "_SYSTEMD_UNIT": "flanneld.service" }]
  pos_file flanneld.pos
  tag flanneld
  read_from_head true
</source>

<filter kubernetes.**>
  type kubernetes_metadata
  verify_ssl true
</filter>
EOF

if [[ -n "$AWS_ELASTICSEARCH_ENDPOINT" && -n "$AWS_REGION" ]]
then
echo "Starting fluentd with aws elasticsearch configuration!"
cat << EOF >> ${conf_file}

<match **>
  type aws-elasticsearch-service
  log_level info
  include_tag_key true
  logstash_format true
  logstash_prefix ${FLUENTD_LOGSTASH_PREFIX}
  buffer_type ${FLUENTD_BUFFER_TYPE}
  $([ "${FLUENTD_BUFFER_TYPE}" == "file" ] && echo buffer_path ${FLUENTD_BUFFER_PATH})
  buffer_chunk_limit ${FLUENTD_BUFFER_CHUNK_LIMIT}
  buffer_queue_limit ${FLUENTD_BUFFER_QUEUE_LIMIT}
  flush_interval ${FLUENTD_FLUSH_INTERVAL}
  retry_limit ${FLUENTD_RETRY_LIMIT}
  $([ "${FLUENTD_DISABLE_RETRY_LIMIT}" == "true" ] && echo disable_retry_limit)
  retry_wait ${FLUENTD_RETRY_WAIT}
  max_retry_wait ${FLUENTD_MAX_RETRY_WAIT}
  num_threads ${FLUENTD_FLUSH_THREADS}
  <endpoint>
    url ${AWS_ELASTICSEARCH_ENDPOINT}
    region ${AWS_REGION}
  </endpoint>
</match>
EOF
fi

exec td-agent